### ISSUE TITLE
when I input some sql that contains Chinese vocabulary ,it Separate with space

### ISSUE THREAD

**Issue by BaooLi** [zeroturnaround/sql-formatter#45] opened 2018-06-05 07:10 UTC
when I input some sql that contains Chinese vocabulary ,it Separate with space.But in some of the existing web sites that can format SQL,it can be format correctly without space.Please resolve this question.
try this example use your sql-formatter:
```
select
  dt,
  eventid,
  abid,
  parameters ['btn'],
  count(1) as 次数,
  count (distinct udid) as 人数
from
  matrix_log.dwv_bobo_sdk
where
  dt = '20180122'
  and hour = '05'
limit
  5
```

**Comment by andrestaht** [comment] 2018-06-05 08:06
Duplicate of #33

**Closed** 2018-06-05 08:06 UTC

**Comment by BaooLi** [comment] 2018-06-08 03:21
I still don't know how to resolve this question,even if I've tried it that update tokenizer.js instead of the existing regex function
```
Tokenizer.prototype.createWordRegex = function createWordRegex() {
    var specialChars = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : [];

    return new RegExp(`^([A-Za-z\u00C0-\u00D6\u00D8-\u00f6\u00f8-\u00ff` + specialChars.join("") + "]+)");
};
```
but it did not work
please tell me how to resolve this bug


![_886751c1-20e8-4293-8d88-4ee76010cc21](https://user-images.githubusercontent.com/31795388/41137514-08294aee-6b0e-11e8-9444-8dc9e0942f24.png)

**Comment by tracybug** [comment] 2019-06-04 03:46
@BaooLi 兄弟他给的解决方案 匹配一下中午字符就可以了 \u4e00-\u9fa5
