### ISSUE TITLE
It will insert Chinese spaces into the character, If my sql string contains Chinese characters

### ISSUE THREAD

**Issue by codingwangxiansen** [zeroturnaround/sql-formatter#107] opened 2020-10-19 02:17 UTC
It will insert Chinese spaces into the character, If my sql string contains Chinese characters

**Comment by nene** [comment] 2021-01-21 17:45
Please be more specific. The following seems to work as expected:

```sql
SELECT * from mytable where field = "漢字"
```

results in:

```sql
SELECT
  *
from
  mytable
where
  field = "漢字"
```

**Comment by nene** [comment] 2021-01-21 18:25
Aha, I see. A duplicate of #91

**Closed by nene** 2021-01-21 18:25 UTC
Labels: unable to reproduce
