### ISSUE TITLE
enclose strings in quotes when replacing placeholders

### ISSUE THREAD

**Issue by dwelle** [zeroturnaround/sql-formatter#42] opened 2018-04-27 09:54 UTC
following

```js
sqlFormatter.format(`SELECT ?`, { params: [ "Sophie's choice" ] })
```

should yield (note the escaped `'`):

```sql
SELECT
    'Sophie''s choice'
```

currently it yields:

```sql
SELECT
    Sophie's choice
```

meanwhile, for anyone interested, you can wrap the param yourself before passing:

```js
params.map( param => {

    return typeof param === "string"
        ? "'" + param.replace(/'/g, "''") + "'"
        : param;
});
```

**Comment by kallaspriit** [comment] 2019-09-23 10:47
Or a more generic function that also handles parameter arrays recursively.

```
function formatParams(params: unknown[] | unknown | undefined): unknown[] | unknown | undefined {
  // recursively handle arrays of parameters
  if (Array.isArray(params)) {
    return params.map(param => formatParams(param));
  }

  // quote string parameters
  if (typeof params === "string") {
    return `'${params.replace(/'/g, "''")}'`;
  }

  // return other parameter types as-is
  return params;
}
```

Usage:

`sqlFormatter.format(query, { params: formatParams(params) })`

**Comment by 8balloon** [comment] 2019-10-17 20:17
@kallaspriit Here's an even more generic version that supports named placeholders:

```
function formatParams (params) {
    // recursively handle arrays of parameters
    if (Array.isArray(params)) {
        return params.map(param => formatParams(param))
    }
    
    // recursively handle named parameter objects
    if (params && typeof params === 'object') {
        let formattedParams = {}
        Object.entries(params).forEach(([key, value]) => {
            formattedParams[key] = formatParams(value)
        })
        return formattedParams
    }

    // quote string parameters
    if (typeof params === 'string') {
        return `'${params.replace(/'/g, "''")}'`
    }

    // return other parameter types as-is
    return params
}
```

**Comment by nene** [comment] 2022-05-19 15:46
Escaping is currently left to the user, so this is by design. I've improved the docs to clarify this.

Proper escaping of parameters is really out of scope for this library. Even the parameters replacement feature itself is really in here only because of historic reasons.

Closing this issue.

**Closed by nene** 2022-05-19 15:46 UTC
Labels: enhancement
